### ISSUE TITLE
Israeli OS community

### ISSUE THREAD

**Issue by UrielOfir** [github/maintainermonth#101]
### Title

Israeli OS community

### Author or authors

Uriel Ofir

### Description

We have a local Israeli open-source community.

We are very active on our Discord server - https://discord.gg/WztShUnu.

Our site allows you to easily find information about Israeli open-source projects.

The community is young, having only been active for a few months. But we got a lot of significant achievements.

We open-source parties where we help people find their next step in the open-source world.

### Resource link

https://opensource-il.vercel.app/

### Conent type

community and data about OS in Israel

### Related topics

community.

**Comment by abbycabs** [comment]
Thanks @UrielOfir! This year, we'll be updating the library to feature interviews / stories from open source maintainers. Do you have any published stories we could link to here?

Otherwise, is your group running any events during the month of May? If so, we'd love to put them on the calendar. https://github.com/github/maintainermonth/issues/new?assignees=&labels=&template=add-to-calendar.yml&title=EVENT_NAME

**Comment by UrielOfir** [comment]
Hi @abbycabs , 
If I will write a post on a blog about our community would it count as a story?
As for an event, I add this one- https://github.com/github/maintainermonth/issues/106. Is it a relevant event?

Uriel :)

**Comment by abbycabs** [comment]
We're looking for stories that highlight maintainers specifically. Do you have a blog post about a maintainer?

**Comment by UrielOfir** [comment]
I can write a post about our community and the projects I maintain in Medium.
What is the deadline to send you the post?

**Comment by abbycabs** [comment]
Anytime during the month of May

**Comment by UrielOfir** [comment]
Unfortunately, I won't be able to write a post due to my busy schedule.

My interview for the Sustain podcast went well and I had a wonderful experience. So I'll settle for that.

Thank you for the opportunity.
