### ISSUE TITLE
Open-source party with the Israel OS community

### ISSUE THREAD

**Issue by UrielOfir** [github/maintainermonth#106]
### Event Name

Open-source party with the Israel OS community

### Event Date

05/29

### Start time in UTC

17:00

### End time in UTC

20:00

### Event Type

meetup

### Organizer name

Uriel Ofir

### Event URL

https://discord.gg/9w6ZWuPe

### Event Description

Open-source parties are part of our OS community tradition.

Everyone comes up and introduces themselves in the context of open-source.

Working together to figure out how each one can proceed and how to make connections with each participant.

**Comment by abbycabs** [comment]
Hi @UrielOfir do you have an expected number of participants attending? And maintainers attending? Estimates are fine.

**Comment by UrielOfir** [comment]
I can estimate that from Israel we'll have 20 participants and 5 of them will be maintainers.

**Comment by abbycabs** [comment]
Thanks @UrielOfir - this is live on the site! https://maintainermonth.github.com/schedule/osparty_israel

**Comment by UrielOfir** [comment]
Hi, can we do updates?
I changed the text a bit-
It's online meeting on our Discrod server where everyone comes up and introduces themselves in the context of open-source.
(for the second sentence).

and change the link to this- https://www.meetup.com/maakaf/events/

**Comment by UrielOfir** [comment]
@abbycabs Can you update the event?
