### ISSUE TITLE
Philippine OSS Community

### ISSUE THREAD

**Issue by jofftiquez** [github/maintainermonth#122]
### Title

Open Source Software PH Story

### Author or authors

Joff Tiquez

### Description

Introduction
Hi, my name is [Joff Tiquez](https://bento.me/jofftiquez?ref=blog.ossph.org) I'm the founder of OSSPH and this the story of my open source journey and how I started OSSPH.

**The Past**

![image](https://github.com/github/maintainermonth/assets/8638243/7001a984-756b-4246-b984-0d629a0d6d92)

So, it all started 7 years ago in 2016. I was busy developing an app using Angular and I already knew about open source and how helpful it could be. One day, out of curiosity, I decided to publish my own project on GitHub. I called it Angular HTTP Assist - just a simple module for the $http directive in Angular. It wasn't much, but then a few weeks later, 3 people gave it a star and I was so stoked that I started updating the project more. Long story short, that's why I kept publishing more projects afterwards.

![image](https://github.com/github/maintainermonth/assets/8638243/76a1d9c7-4670-4582-8720-e22ab4d68fbf)

So, fast forward to 2017, and I made my biggest project yet: Vue Stripe. You can check it out at [https://vuestripe.com](https://vuestripe.com/?ref=blog.ossph.org). Essentially, it's a bunch of custom components and plugins for Stripe Checkout and Stripe Elements, made specifically for Vue.js. This project is my baby and has almost 1k stars on GitHub, 15K downloads per week, and it's been used by nearly 700 other open source projects (not including the private ones). Plus, I've got 30 contributors from all around the world. I've been keeping this thing going for 6 years now and honestly, it's changed my life. Even with all the pandemic craziness in 2020, something good happened!

![image](https://github.com/github/maintainermonth/assets/8638243/a48803ef-ef82-44f2-a43d-bd44ed43e6b6)

One day I got an email from a guy named Chris at Stripe asking me about my project, Vue Stripe. He wanted to know how it was doing, how many issues there were, and all that. I didn't think much of it at first, but then we started talking more and he ended up offering to support my project! From funding to connections in the tech world, they really helped me out. I even got to do a guest appearance on GitHub's Open Source Friday with Mish Manners - you can find it on YouTube if you're interested!

All of this really motivated me and boosted my career. I met new people, made new friends (shoutout to Chris and his team at Stripe), and most importantly, I got to showcase Filipino talent on the global stage. With all the good things happening, I started thinking about how I could help other Filipino devs get the same opportunities. I knew there were so many talented folks out there who just needed a platform to showcase their work.

So, I came up with an idea: why not start an organization that helps Filipino devs learn about open source and highlights their work? And that's exactly what I did! I wanted to create a space where other devs could show what they've got and get the recognition they deserved.

In October 2021, I started building OSSPH. Ya know, the typical process: figuring out a name, buying a domain, and building a website. But life got pretty hectic with work and personal stuff, and I had to put the project on hold for a bit. To be honest, I was feeling super demotivated and stressed, and almost gave up completely since I was the only one working on it. But somehow I managed to push through, and almost a year later, OSSPH was finally launched!

**The Present**

![image](https://github.com/github/maintainermonth/assets/8638243/31f1bbbd-9742-4784-980f-1813493dc325)

Today I am not alone, and OSSPH has grew significantly and is still growing everyday. We now have almost [1.1K discord members](https://discord.com/invite/4ujGbRJyDN?ref=blog.ossph.org), [5.5k Facebook followers](https://www.facebook.com/ossph.org), [6 community partners](https://ossph.org/?ref=blog.ossph.org), and [14 hardworking volunteers](https://ossph.org/team?ref=blog.ossph.org) which I thank with all of my heart! The discord community is as lively as ever and everyone is interacting with other daily. It's really good see how members are sharing their knowledge and helping each other. From only 1, to almost a thousand members, I am really proud of what OSSPH has accomplished in just a few months!

**The Future**

But hey, this is just the start of our journey and the road ahead is long. Our goals are ambitious, but we're determined to see them through. You see, [the problem with open source is bigger](https://www.theregister.com/2023/02/15/corejs_russia_open_source/?ref=blog.ossph.org) than just incomplete issues and pesky pull requests. The real issue lies with hardworking maintainers who aren't receiving enough support, or sometimes, no support at all.

I was one of the lucky ones since Stripe had an initiative to solve this very problem in their ecosystem, and I happened to be developing a library for them. But let's be real, not every company is like Stripe. Most companies today aren't giving back to the open source community, even though they're earning millions of dollars from it. Sure, it's not required, but seriously, can't they spare some amount to give back to the community that built their success? We can't blame them, but we want to change that.

So, we're taking it upon ourselves to educate everyone, from maintainers to companies and organizations that are benefitting from open source. We want to create an ecosystem where everyone gets what they need. This initiative includes helping developers build high-quality projects and documentations for their work, and teaching them how to properly maintain their projects.

Additionally, we want to build a bridge between maintainers and companies, starting in the Philippines, to better understand the open source community and maybe offer better opportunities to maintainers. We're in this for the long haul, and we're serious about making a positive impact on the open source community.

### Resource link

https://ossph.org

### Conent type

Story of OSSPH and the Philippine open source community

### Related topics

open-source, community, oss, maintainers

**Comment by abbycabs** [comment]
Huge thanks for this @jofftiquez! Love this story.

Is there a link we can link to with this content? For context, we'll be listing stories on this page: https://maintainermonth.github.com/library And linking it out to your full story.

**Comment by jofftiquez** [comment]
> Huge thanks for this @jofftiquez! Love this story.
> 
> Is there a link we can link to with this content? For context, we'll be listing stories on this page: [maintainermonth.github.com/library](https://maintainermonth.github.com/library) And linking it out to your full story.

Hi @abbycabs thank you for the appreciation <3

Yes, here's the updated link to the article itself. Let me know if there's anything more I can provide. https://blog.ossph.org/the-story-of-open-source-software-ph-ossph/

**Comment by abbycabs** [comment]
@jofftiquez your story is live in the Library!
https://maintainermonth.github.com/library

Here's our asset kit to make it as easy as possible to spread the word:
https://gist.github.com/abbycabs/39f8f8577f2a7dae3a9b1c88b9ff6aeb

**Comment by jofftiquez** [comment]
> @jofftiquez your story is live in the Library! [maintainermonth.github.com/library](https://maintainermonth.github.com/library)
> 
> Here's our asset kit to make it as easy as possible to spread the word: [gist.github.com/abbycabs/39f8f8577f2a7dae3a9b1c88b9ff6aeb](https://gist.github.com/abbycabs/39f8f8577f2a7dae3a9b1c88b9ff6aeb)

This is great! Thank you so much @abbycabs <3
