### ISSUE TITLE
EVENT_NAME

### ISSUE THREAD

**Issue by adamj89** [github/maintainermonth#123]
### Event Name

Ottawa Green Software Foundation Meetup - Hybrid Event

### Event Date

24-May-2023

### Start time in UTC

13:00

### End time in UTC

14:30

### Event Type

meetup

### Organizer name

Green Software Foundation

### Event URL

https://www.meetup.com/gsf-canada/events/293112123

### Event Description

This is the first Green Software Foundation meetup in Ottawa. We'll have insightful talks on the Principles of Sustainable Green Software as well as Sustainable DevOps. You'll also learn about how you can help the Green Software Foundation maintain projects and patterns which will help reduce the carbon impact of software. Don't miss out on this opportunity to learn, connect, and engage; mark your calendars and prepare for an exciting morning of discussions, and connections!

**_The event will be hybrid._** You are welcome to join in person at the Microsoft Ottawa office at 100 Queen Street, Suite 500, Ottawa, Ontario, K1P 1J9. Or we'll see you online!

**9:00am EDT** - Welcome and networking

**9:30am EDT** - Principles of Green Software Engineering - Abhishek Gupta, Senior Responsible AI Leader & Expert, BCG
The Principles of Sustainable Green Software Engineering are a core set of competencies needed to define, build and run green software applications.

**10:00am EDT** Sustainable DevOps - Tajinder Singh, Solutions Engineer, Github
Organizations are talking about Green Software, Green Cloud but what about DevOps? Green And Sustainable DevOps is as important as software and the cloud. Learn more about best practices and how to use GitHub And Azure to run Sustainable DevOps Pipelines.

10:30am EDT - Close and networking

### Participants

30

### Maintainers

30

**Comment by adamj89** [comment]
This event is part of the meetup activity of the Green Software Foundation - more information available at https://greensoftware.foundation. GSF is part of the Linux Foundation.

**Comment by abbycabs** [comment]
Thanks @adamj89! Your event is listed on the schedule: https://maintainermonth.github.com/schedule/green-software-foundation-meetup

**Comment by abbycabs** [comment]
@adamj89 please take a look at our [Asset Kit](https://gist.github.com/abbycabs/39f8f8577f2a7dae3a9b1c88b9ff6aeb) to share widely!
