### ISSUE TITLE
EVENT_NAME

### ISSUE THREAD

**Issue by LucioMSP** [github/maintainermonth#131]
### Event Name

GitHub Open Source CDMX v4

### Event Date

26/05

### Start time in UTC

19:00

### End time in UTC

21:00

### Event Type

meetup

### Organizer name

Vicente Guzmán

### Event URL

https://www.meetup.com/es-ES/githublatam/events/293024073/

### Event Description

¡Hola GitHub-eros!

Nos complace anunciar que tendremos nuestro cuarto (4to) evento del año, nuevamente en las oficinas de Platzi México.

En esta oportunidad tendremos la participación de dos MLSA (Microsoft Learn Student Ambassadors) quienes nos impartirán: "Conectando el mundo físico y digital".

Fátima es estudiante de ingeniería en comunicaciones y electrónica en el IPN. Gold Microsoft Learn Student Ambassador, miembro de comunidades como Technolatinas, X-Women y miembro fundador de Nopalito Tech.

Berenice es estudiante de Ingeniería Mecatrónica en la Facultad de Ciencias de la Electrónica de BUAP. Inició impartiendo tutorías sobre electrónica, robótica y programación como voluntaria en la rama WIE IEEE BUAP.

Descripción:
El Internet de las cosas (IoT, por sus siglas en inglés) se refiere a la interconexión de dispositivos y objetos cotidianos a través de internet, permitiendo la comunicación y el intercambio de datos en tiempo real. Desde los electrodomésticos hasta los sistemas de transporte, la IoT está transformando la forma en que interactuamos con el mundo físico.

En esta charla, analizaremos cómo IoT está impulsando la innovación en una variedad de sectores, desde la industria manufacturera hasta la agricultura y la salud.

Además, discutiremos los desafíos y las preocupaciones asociadas con la IoT, como la privacidad y la seguridad. Por último, abordaremos las tendencias futuras en la IoT y cómo pueden impactar nuestra vida diaria a través de una demostración con Azure IoT Central.

Si te interesa descubrir cómo la IoT está cambiando el mundo que nos rodea y qué podemos esperar en el futuro cercano, ¡no te pierdas esta charla!

Asiste Presencialmente
Ven y acompañamos a nuestro cuarto evento del año, en el que podrás asistir en vivo y aprender más sobre como utilizar GitHub.

Además, ¡habrá muchas sorpresas (regalitos)!

No te lo pierdas y dile a tus amigos....

### Participants

120

### Maintainers

20

**Comment by abbycabs** [comment]
Your event is live on the website! https://maintainermonth.github.com/schedule/CDMX-v4

Here's our asset kit to make it as easy as possible to share out:
https://gist.github.com/abbycabs/39f8f8577f2a7dae3a9b1c88b9ff6aeb
