### ISSUE TITLE
EVENT_NAME

### ISSUE THREAD

**Issue by kungfuchicken** [github/maintainermonth#139]
### Event Name

Summer Student Maintainer Meetup

### Event Date

05/22

### Start time in UTC

11:30

### End time in UTC

1:30

### Event Type

meetup

### Organizer name

Kate Holdener

### Event URL

https://oss-slu.github.io/

### Event Description

Are you staying in Saint Louis for the summer and looking for a way to contribute to meaningful software projects, build up your resume with programming experience, and connect with other students in the department? Joining Open Source with SLU community may be the right move for you. [Open Source with SLU](https://oss-slu.github.io/) is hosting an open community meeting on Monday, May 22 from 11:30am till 1:30pm in ISE 210. This will be a hands-on meeting, where we’ll introduce you to our existing projects and codebases, help you setup a development environment, and outline the next steps. Bring your laptop and get ready to learn and contribute. Since this meeting runs over lunch time, we’ll order pizza (based on the number of people in attendance).

The opportunity to be part of the Open Source with SLU community is open to all students. Note, that this is volunteer position (not a paid position). If you are not around this summer and are bummed out to miss this meeting, we’ll have more opportunities for you to get involved in the Fall semester.

**Comment by abbycabs** [comment]
Hi @kungfuchicken -- so sorry I was ooo for a bit and missed getting this on the site before it happened. Do you still want it listed? or do you have an event later on we could share?
