### ISSUE TITLE
EVENT_NAME

### ISSUE THREAD

**Issue by olybeke** [github/maintainermonth#141]
### Event Name

Empowering Open Source Contributors and Building Future Leaders

### Event Date

05/26

### Start time in UTC

17:00

### End time in UTC

19:00

### Event Type

talk

### Organizer name

CHAOSS Project Africa

### Event URL

https://twitter.com/i/spaces/1yoKMZzgemdGQ

### Event Description

In this Twitter Space with CHAOSS Project Africa, we will hear from some maintainers who actively contribute and maintain the [CHAOSS Project](https://chaoss.community/) talk about their journey, and how they navigate their daily lives as a maintainer.

### Participants

50 -100

### Maintainers

3

**Comment by abbycabs** [comment]
Thanks @olybeke! This is live on the website now: https://maintainermonth.github.com/schedule/chaoss-africa

Here's a quick asset kit to help you spread the word: https://gist.github.com/abbycabs/39f8f8577f2a7dae3a9b1c88b9ff6aeb
