### ISSUE TITLE
TITLE

### ISSUE THREAD

**Issue by feranmiokafor1** [github/maintainermonth#142]
### Title

Maintainer Month 2023: Behind the scenes with Rushmore Mushambi

### Author or authors

Rushmore Mushambi

### Description

At SurrealDB, we're keen on celebrating the efforts made by our maintainers. Rushmore Mushambi is a senior software engineer at SurrealDB and is focused on building out and  maintaining our Rust API layer and WebAssembly library. He shares his journey as an engineer, how he got interested n rust, cool projects he's worked on in the past and everything in between. 

### Resource link

https://surrealdb.com/blog/maintainer-month-2023-behind-the-scenes-with-rushmore-mushambi

### Conent type

Blog Post

### Related topics

Open source, database, rust

**Comment by abbycabs** [comment]
Huge thanks @feranmiokafor1 -- this is live on the website! So glad to see SurrealDB participating this year :)

Here's our asset kit to make it easy for you to share: https://gist.github.com/abbycabs/39f8f8577f2a7dae3a9b1c88b9ff6aeb

**Comment by LadyKerr** [comment]
@LadyKerr testing notifications!
