### ISSUE TITLE
TITLE

### ISSUE THREAD

**Issue by CBID2** [github/maintainermonth#150]
### Title

4 Tips to Transition from Contributorhood to Maintainership

### Author or authors

Chrissy Codes 

### Description

In honor of Maintainer's Month, my blog post focuses on four tips to transition from contributor to open source maintainer. 

### Resource link

https://chrissycodes.hashnode.dev/4-tips-to-transition-from-contributorhood-to-maintainership

### Content type

Blog Post

### Related topics

Open Source

**Comment by abbycabs** [comment]
Thanks @CBID2! This is live on the website!

Here's our asset kit to make it easy for you to share: https://gist.github.com/abbycabs/39f8f8577f2a7dae3a9b1c88b9ff6aeb
