### ISSUE TITLE
Maintainer Story: @mumoshu

### ISSUE THREAD

**Issue by mumoshu** [github/maintainermonth#154]
### Title

Maintainer Month 2023: Behind the scenes with Yusuke Kuoka

### Author or authors

Yusuke Kuoka

### Description

Hi 👋 

In honor of Maintainer's Month, my blog post focuses on encouraging everyone to get involved in open-source, by introducing how open-source helped motivate me and progress my career as a software developer.

### Resource link

https://surrealdb.com/blog/maintainer-month-2023-behind-the-scenes-with-yusuke-kuoka

### Conent type

Blog Post

### Related topics

Open Source

**Comment by abbycabs** [comment]
Thanks for another story @mumoshu! Should be live shortly on the website
