### ISSUE TITLE
[Event] OpenUK Online #1: Maintainers, Maintainers, Maintainers!

### ISSUE THREAD

**Issue by jamietanna** [github/maintainermonth#184]
### Event Name

OpenUK Online #1: Maintainers, Maintainers, Maintainers!

### Event Date

05/22

### Start time in UTC

11:00

### End time in UTC

12:00

### Event Type

meetup

### Organizer name

OpenUK

### Event URL

https://www.meetup.com/openuk/events/300878789/

### Event Description

Join us on Wednesday 22nd May for the FIRST OpenUK Online Meetup, our online-only event for OpenUK community members.

This will be a lunch-time webinar, where you'll get to hear from maintainers about their highs and lows about working in the open, which ties into May being [GitHub's Maintainer Month](https://maintainermonth.github.com/)

### Participants

30

### Maintainers

10

**Comment by karasowles** [comment]
Thank you! Added it here, should show up on the site soon: https://github.com/github/maintainermonth/blob/main/content/events/2024-05-22-open-uk.md

This looks like so much fun!

**Comment by jamietanna** [comment]
Thanks! Looks like https://github.com/github/maintainermonth/pull/185 is needed to unblock the build :crossed_fingers:
