### ISSUE TITLE
New Event: CHAOSS Burnout and Mental Health Session

### ISSUE THREAD

**Issue by Ruth-ikegah** [github/maintainermonth#33]
Hi Folks,

[CHAOSS](https://chaoss.community/) will love to add an event to the website schedule. Here are the details of this event:

- Event Title: Burnout and Mental Health in Open Source
- Description: Burnout is a relatable issue, almost everyone has been there– and it’s something we see quite often in open source. CHAOSS is hosting an interactive working group session to understand how maintainers manage burnout and talk about how to facilitate conversations about burnout and mental health in their open source communities. We will also discuss the 
[Project Burnout metric](https://chaoss.community/metric-project-burnout/) from our DEI working group.
- Date: June 17th
- Time: 12 pm Central Time
- Registration Link: https://forms.gle/HfLhPaD4C8gdb7QY9

I have also attached the flyer image! Please let me know if you need any other details.

![Original Project Burntout (1)](https://user-images.githubusercontent.com/62059002/170263485-bb6405c2-ccb9-45ad-83f0-8c476ecf5cfc.png)

cc: @karasowles

**Comment by karasowles** [comment]
thanks Ruth! Sorry, forgot to update the Issue that it was posted here: https://maintainermonth.github.com/schedule/CHAOSS

Looking forward to this!

**Comment by Ruth-ikegah** [comment]
> thanks Ruth! Sorry, forgot to update the Issue that it was posted here: https://maintainermonth.github.com/schedule/CHAOSS
> 
> Looking forward to this!

Thanks, Kara!
