### ISSUE TITLE
Hide "packages" on the right side if not currently used

### ISSUE THREAD

**Issue by eddiejaoude** [github/maintainermonth#39]
I think it is great to hide features that are not used, they can always be brought back if they are needed

<img width="1649" alt="Screenshot 2022-06-06 at 17 28 18" src="https://user-images.githubusercontent.com/624760/172210870-82000177-3e24-4f5d-8a9e-9befb1b89c32.png">

**Comment by ljharb** [comment]
While you can manually change this by clicking the "gear" icon on repos you control, I agree it should just omit empty sections.

**Comment by ljharb** [comment]
@abbycabs done how/when? I just enabled the packages tab on https://github.com/ljharb/qs, and it's still showing up despite there being no packages published.

**Comment by abbycabs** [comment]
I manually turned it off for this repo like Eddie suggested

**Comment by ljharb** [comment]
ahhh i misunderstood the issue then :-) i got excited thinking you were going to auto-hide those sections everywhere when they were empty

**Comment by abbycabs** [comment]
Ah, that's a great feature request for github.com/community
