### ISSUE TITLE
Edit getting started guide inside the readme

### ISSUE THREAD

**Issue by orama254** [github/maintainermonth#44]
Greetings team,

From the getting started guide on the readme, the second step on usage is showing that one should use yarn start in development mode which causes an error as shown below:

#### command:
![change-from-yarn-start-to yarn-dev](https://user-images.githubusercontent.com/50571688/172484193-3eb26b1a-4da7-4977-94be-5fa347ad1746.png)

#### error message:
![change-from-yarn-start-to yarn-dev-CMD](https://user-images.githubusercontent.com/50571688/172484352-29919d3b-eea9-477f-83d9-ca15d76de856.png)
---
<br />

A solution would be to change the instructions from yarn start to yarn dev, which is what I used to start my development environment

**Comment by abbycabs** [comment]
sorry for the delay here -- I'm unable to recreate this issue. Closing since this is a bit stale, but feel free to reopen!
