### ISSUE TITLE
Fix README.md Installation & Setup Guide

### ISSUE THREAD

**Issue by prathamshroff** [github/maintainermonth#89]
It would be nice to update the README for all maintainers & developers for the new 2023 content. One could reference the `README-old.md` and easily do it.

Also, it throws an error on step 2 of setup at `yarn start` and that should be updated to `yarn dev`. It would also be helpful to mention that one needs `yarn` installed and could do so using `brew install yarn` for Mac or include a link to the yarn installation page.

If you'd like, I could fix this issue given some guidance and help contribute to this project.

**Comment by abbycabs** [comment]
Thanks @prathamshroff! I updated the README for 2023. I wasn't able to replicate your issues with `yarn dev`.

**Comment by abbycabs** [comment]
We're using yarn start in production. You're welcome to use yarn dev for development mode.
